import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HomeLayout } from "@/modules/home/ui/layouts/home-page";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EDUNOVA",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <StoreProvider>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"

          />
        </StoreProvider>
      </body>
    </html>
  );
}
