import { Course } from "@/types";

function getISODate(dayOffset: number, hour: number, minute: number = 0) {
  const base = new Date();
  const day = new Date(base.setDate(base.getDate() - base.getDay() + dayOffset));
  day.setHours(hour, minute, 0, 0);
  return day.toISOString();
}

export const dummyCourses: Course[] = [
  {
    _id: "1",
    id: "C001",
    subject: {
      _id: "s1",
      id: "MATH101",
      name: "Toán cao cấp",
      description: "Giải tích và đại số tuyến tính",
      timeAllocation: "45",
      curriculums: [],
      documents: [],
      _destroy: false,
    },
    lecturer: {
      _id: "u1",
      email: "gv1@example.com",
      displayName: "TS. Nguyễn Văn A",
      avatar: "",
      role: "lecturer",
      isActive: true,
    },
    students: [],
    semester: {
      _id: "sem1",
      name: "Học kỳ 1",
      startDate: new Date(),
      endDate: new Date(),
    },
    startDate: getISODate(1, 8),
    endDate: getISODate(1, 10),
    status: "active",
    room: "A101",
  },
  {
    _id: "2",
    id: "C002",
    subject: {
      _id: "s2",
      id: "ENG201",
      name: "Tiếng Anh chuyên ngành",
      description: "Ngôn ngữ học và giao tiếp kỹ thuật",
      timeAllocation: "30",
      curriculums: [],
      documents: [],
      _destroy: false,
    },
    lecturer: {
      _id: "u2",
      email: "gv2@example.com",
      displayName: "ThS. Trần Thị B",
      avatar: "",
      role: "lecturer",
      isActive: true,
    },
    students: [],
    semester: {
      _id: "sem1",
      name: "Học kỳ 1",
      startDate: new Date(),
      endDate: new Date(),
    },
    startDate: getISODate(3, 13),
    endDate: getISODate(3, 15),
    status: "active",
    room: "B202",
  },
  {
    _id: "3",
    id: "C003",
    subject: {
      _id: "s3",
      id: "IT301",
      name: "Lập trình Web",
      description: "Next.js và React",
      timeAllocation: "60",
      curriculums: [],
      documents: [],
      _destroy: false,
    },
    lecturer: {
      _id: "u3",
      email: "gv3@example.com",
      displayName: "ThS. Lê Văn C",
      avatar: "",
      role: "lecturer",
      isActive: true,
    },
    students: [],
    semester: {
      _id: "sem1",
      name: "Học kỳ 1",
      startDate: new Date(),
      endDate: new Date(),
    },
    startDate: getISODate(5, 9),
    endDate: getISODate(5, 12),
    status: "active",
    room: "C303",
  },
  {
    _id: "4",
    id: "C004",
    subject: {
      _id: "s4",
      id: "PHY111",
      name: "Vật lý đại cương",
      description: "Cơ học và Nhiệt học",
      timeAllocation: "45",
      curriculums: [],
      documents: [],
      _destroy: false,
    },
    lecturer: {
      _id: "u4",
      email: "gv4@example.com",
      displayName: "PGS. Nguyễn Hữu D",
      avatar: "",
      role: "lecturer",
      isActive: true,
    },
    students: [],
    semester: {
      _id: "sem1",
      name: "Học kỳ 1",
      startDate: new Date(),
      endDate: new Date(),
    },
    startDate: getISODate(2, 10),
    endDate: getISODate(2, 12),
    status: "active",
    room: "D404",
  },
  {
    _id: "5",
    id: "C005",
    subject: {
      _id: "s5",
      id: "HIS101",
      name: "Lịch sử văn minh thế giới",
      description: "Từ cổ đại đến hiện đại",
      timeAllocation: "30",
      curriculums: [],
      documents: [],
      _destroy: false,
    },
    lecturer: {
      _id: "u5",
      email: "gv5@example.com",
      displayName: "TS. Lê Thanh H",
      avatar: "",
      role: "lecturer",
      isActive: true,
    },
    students: [],
    semester: {
      _id: "sem1",
      name: "Học kỳ 1",
      startDate: new Date(),
      endDate: new Date(),
    },
    startDate: getISODate(4, 14, 15),
    endDate: getISODate(4, 15, 45),
    status: "ended",
    room: "E505",
  },
];
